---
- name: "Clear gathered facts"
  meta: clear_facts

- name: "Gather Facts"
  setup: ""

- name: "Generate master node configuration for cluster"
  template:
    src: "rethinkdb.conf.j2"
    dest: "{{ startup_config_path }}/rethinkdb.conf"
  when: master_node == ansible_host
  notify: "Restart master node"

- name: "Generate slave node configuration for cluster"
  template:
    src: "rethinkdb.conf.j2"
    dest: "{{ startup_config_path }}/rethinkdb.conf"
  when: ansible_host != master_node
  notify: "Restart slave nodes"