---
- hosts: all
  tasks:
    - name: "Set yum epel repo"
      yum:
        name: "{{ epel_url }}-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: "present"
      when: ansible_distribution == "CentOS"

    - name: "Set gpg key for epel repo"
      rpm_key:
        key: "{{ epel_key_url }}-{{ ansible_distribution_major_version }}"
        state: "present"
      when: ansible_distribution == "CentOS"

    - name: "Install dependencies"
      yum:
        name: "python-pip"
        state: "present"
      when: ansible_distribution == "CentOS"
    
    - name: "Install ubuntu dependencies"
      apt:
        name: "python-pip"
        state: "present"
      when: ansible_distribution == "Ubuntu"

    - name:
      pip:
        name: "rethinkdb"
  vars:
    epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest"
    epel_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL"